name: Test on push and publish

on:
  push:
    branches:
      - master
      - main
      - track/**

  pull_request:
    branches:
      - master
      - main
      - track/**

jobs:

  publish-charm:
    name: Publish Charm
    runs-on: ubuntu-latest
    steps:
      - name: Run the tests on push
        if: (github.event_name == 'push')
        id: tests
        uses: ./.github/workflows/ci.yaml
      - name: Checkout
        if: (((github.event_name == 'pull_request') && always()) || ((github.event_name == 'push') && steps.tests.outcome == 'success'))
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Select charmhub channel
        uses: canonical/charming-actions/channel@1.0.3
        id: channel
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@1.0.3
        with:
          credentials: "${{ secrets.CHARMCRAFT_CREDENTIALS }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "${{ steps.channel.outputs.name }}"
